#ifndef NCPAPROP_COMMON_H_INCLUDED
#define NCPAPROP_COMMON_H_INCLUDED

#define NCPAPROP_MAJOR_VERSION 2
#define NCPAPROP_MINOR_VERSION 2
#define NCPAPROP_BUILD_VERSION 1
#define NCPAPROP_VERSION NCPAPROP_MAJOR_VERSION.NCPAPROP_MINOR_VERSION.NCPAPROP_BUILD_VERSION

#include "NCPACommon.h"

#endif
